services:
  soup.api:
    image: soup.api
    restart: on-failure
    build:
      context: ./src/Soup.Api
      dockerfile: ./Dockerfile
    ports:
      - '5000:8080'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SOUP_API_Auth__Jwt__Authority: http://auth.wiedersehen.api:8080
      SOUP_API_Auth__Jwt__ValidateAudience: false
      SOUP_API_Auth__Jwt__ValidIssuers__0: http://auth.wiedersehen.api:8080
      SOUP_API_Auth__Jwt__ValidIssuers__1: http://localhost:5002
      SOUP_API_Auth__Jwt__RequireHttpsMetadata: false

  auth.wiedersehen.api:
    image: auth.wiedersehen
    build:
      context: ./src/Auth.Wiedersehen
      dockerfile: ./Dockerfile
    ports:
      - '5002:8080'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AUTHW_Database__ConnectionString: Server=auth.wiedersehen.db;Database=auth_wiedersehen;User Id=sa;Password=Qwert1234_;

  auth.wiedersehen.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Qwert1234_
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - auth_sql_vol:/var/opt/mssql

volumes:
  auth_sql_vol: