services:
  soup-api:
    image: soup.api
    restart: on-failure
    build:
      context: ./src/Soup.Api
      dockerfile: ./Dockerfile
    ports:
      - '5000:8080'
    depends_on:
      - auth-wiedersehen-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SOUP_API_Auth__Jwt__Authority: http://auth-wiedersehen-api:8080
      SOUP_API_Auth__Jwt__ValidateAudience: false
      SOUP_API_Auth__Jwt__ValidIssuers__0: http://auth-wiedersehen-api:8080
      SOUP_API_Auth__Jwt__ValidIssuers__1: http://localhost:5002
      SOUP_API_Auth__Jwt__RequireHttpsMetadata: false

  auth-wiedersehen-api:
    image: auth-wiedersehen
    build:
      context: ./src/Auth.Wiedersehen
      dockerfile: ./Dockerfile
    ports:
      - '5002:5002'
    depends_on:
      - auth-wiedersehen-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:5002"
      AUTHW_ConnectionStrings__ApplicationDB: Host=auth-wiedersehen-db;Database=auth_wiedersehen;Username=postgres;Password=Qwert1234_;
      AUTHW_ConnectionStrings__ConfigurationDB: Host=auth-wiedersehen-db;Database=configuration_db;Username=postgres;Password=Qwert1234_;
      AUTHW_ConnectionStrings__PersistentGrandDB: Host=auth-wiedersehen-db;Database=persisted_grant_db;Username=postgres;Password=Qwert1234_;

  auth-wiedersehen-db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: Qwert1234_
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb

#  auth-wiedersehen-db:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    restart: always
#    environment:
#      ACCEPT_EULA: Y
#      SA_PASSWORD: Qwert1234_
#      MSSQL_PID: Developer
#    ports:
#      - "1433:1433"
#    volumes:
#      - auth_sql_vol:/var/opt/mssql

volumes:
  auth_sql_vol: